repos:
  - name: VulnerableApp
    local_path: ./repos/VulnerableApp
    scanners:
      - plugin: SemgrepPlugin
        config:
          configs: ["p/owasp-top-ten"]   # or your custom rules dir
          # no_git: true                 # uncomment if you ever see git issues
          include: ["**/*.cs","**/*.json","**/*.yaml","**/*.yml","**/*.sh","**/Dockerfile"]
          timeout: 180
      - plugin: OSVScannerPlugin
        config:
          # lockfiles: ["package-lock.json","Pipfile.lock","poetry.lock"]  # optional
