repos:
  - name: VulnerableApp
    url: https://github.com/rossobianero/VulnerableApp.git
    default_branch: main
    local_path: ../VulnerableApp
    scanners:
      - plugin: SemgrepPlugin
        config:
          use_docker: true
          rules:
            - p/owasp-top-ten
            - p/r2c-security-audit
          extra_args:
            - --timeout
            - "180"
      - plugin: OSVScannerPlugin
        config:
          use_docker: true
          extra_args:
            - --lockfile-only
